name: "Github Actions: CI"

on:
  pull_request:
    branches: [ main ]

jobs:
  check_code:
    runs-on: ubuntu-latest
    steps:
      - run: npm run lint
      - run: npm run prettier
      - run: npm test
      - run: npm run build

      
