name: GitHub Actions CI

on:
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Display Actor
              run: echo "${{ github.actor }} is launching pipeline"

            - name: Display Start Time Pipeline
              run: echo "Pipeline started at $(date +'%H:%M:%S')"

            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "14"

            - name: Install dependencies
              run: npm install

            - name: Run Prettier
              run: npm run prettier

            - name: Run ESLint
              run: npm run lint

            - name: Run tests and check coverage
              run: |
                  npm run test -- --coverage
                  COVERAGE=$(cat coverage/lcov-report/greet.js.html | grep -oP 'Statements<\/td><td class="text-right"><strong>\K\d+')
                  echo "COVERAGE: $COVERAGE"
                  if [ $COVERAGE -ge 80 ]; then
                  echo "Code coverage is above 80%: $COVERAGE%"
                  else
                  echo "Code coverage is below 80%: $COVERAGE%"
                  exit 1
                  fi

            - name: Build Project
              run: npm run build

            - name: Display End Time Pipeline
              run: echo "Pipeline finished at $(date +'%H:%M:%S')"

            - name: Display Success Message
              run: echo "PIPELINE SUCCESS WITHOUT ERRORS"
