name: 'GitHub Actions : Continuous Integration'

on:
  pull_request:
    branches: [ main ]

jobs:
  check_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install Dependencies
        run: npm install

      - name: Display Start Time Pipeline
        run: echo "Start Time: $(date +%H:%M:%S)"

      - name: Prettier
        run: npm run prettier

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Display End Time
        run: echo "End Time: $(date +%H:%M:%S)"
