name: Node.js CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Display Start Time
      run: echo "Start Time:$(date +\%H:\%M:\%S)"

    - name: Install dependencies
      run: npm install

    - name: Run Prettier
      run: npm run prettier

    - name: Run Lint
      run: npm run lint
      
    - name: Build
      run: npm run build

    - name: Display End Time
      run: echo "End Time:$(date +%H:%M:%S)"

    - name: Display Success Message
      run: echo "PIPELINE SUCCESS WITHOUT ERRORS"


