name: GitHub Actions 

on:
  pull_request:
    branches: [ main ]

jobs:
  check_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm install
      - run: npm run lint
      - run: npm run prettier
