name: 'GitHub Actions : Continuous Integration'

on:
    pull_request:
        branches: [main]

jobs:
    check_code:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 16.14
            - run: npm install
            - run: npm ci
            - run: npm run lint:fix
            - run: npm run prettier:fix
            - run: npm test
            - run: npm run build
